g/23 adminBulletinOperations
DP2-C1-01-03/Acme-L3-D03 pull request #142
Opened 2023-04-18 21:29 UTC by regescmar1

2023-04-19 14:49 UTC, AntonioRodriguezRuiz submitted a review, later dismissed
You must fix the following things (Some of these were from the other PR, but might as well be fixed here):
- Creation moment must not be editable in the creation form or don't show it
- Don't show the critical field in the list (internationalization reasons)
- Show the "critical" field in the authenticated show as a checkbox

2023-04-19 14:59 UTC, victoriaemc requested changes

2023-04-19 14:59 UTC, victoriaemc commented on src/main/webapp/WEB-INF/views/administrator/bulletin/form.jsp
> +    <acme:input-moment code="administrator.bulletin.form.label.creationMoment" path="creationMoment" />
Since this is not editable by the administrator who creates the bulletin, make it read only

2023-04-19 14:59 UTC, victoriaemc commented on src/main/webapp/WEB-INF/views/authenticated/bulletin/list.jsp
> +		path="critical" width="15%" />
Booleans can't be internationalised. Please show only in form.jsp as a (read only) checkbox

2023-04-20 07:01 UTC, victoriaemc approved these changes
Internationalisation in views now correct

2023-04-20 07:08 UTC, victoriaemc requested changes

2023-04-20 07:08 UTC, victoriaemc commented on src/main/webapp/WEB-INF/views/administrator/bulletin/form.jsp
> +    <acme:input-checkbox code="administrator.bulletin.form.label.critical" path="critical" />
Add this same attribute (but readonly) in authenticated/bulletin/show.jsp

2023-04-20 17:14 UTC, victoriaemc approved these changes
Everything checks out

2023-04-20 17:18 UTC, AntonioRodriguezRuiz approved these changes
Took over the task at the end. I'm approving to have no longer changes requested and because Victoria also approved already

2023-04-20 17:18 UTC, merged