1/14+15 course operations
DP2-C1-01-03/Acme-L3-D03 pull request #71
Opened 2023-03-28 16:16 UTC by kiinami

Closes #10 
Closes #11 
Closes #69 
Closes #70

2023-03-28 18:51 UTC, AntonioRodriguezRuiz requested changes

2023-03-28 18:51 UTC, AntonioRodriguezRuiz commented on src/main/java/acme/features/lecturer/course/LecturerCoursePublishService.java
> +
please remove all of these blank lines

2023-03-28 18:51 UTC, AntonioRodriguezRuiz commented on src/main/java/acme/features/lecturer/course/LecturerCourseUpdateService.java
> +    }
Check that the "code" of the object is not duplicated on any other Course

2023-03-28 18:51 UTC, AntonioRodriguezRuiz commented on src/main/java/acme/features/lecturer/course/LecturerCoursePublishService.java
> +    }
Check that the "code" of the object is not duplicated on any other Course

2023-03-28 18:51 UTC, AntonioRodriguezRuiz commented on src/main/java/acme/features/lecturer/course/LecturerCourseDeleteService.java
> +    }
Maybe this should also delete all the objects that depend on it, such as enrolments and their activities, practicums, etc. We should ask this to the Lecturer on the next follow-up

2023-03-28 18:51 UTC, AntonioRodriguezRuiz commented on src/main/java/acme/features/lecturer/course/LecturerCourseCreateService.java
> +    }
Check the "code" field is not duplicated

2023-03-28 18:51 UTC, AntonioRodriguezRuiz commented on src/main/webapp/WEB-INF/views/lecturer/course/form.jsp
> +  </jstl:choose>
If we moddify a value to a non-valid one before publishing we get this:
![imagen](https://user-images.githubusercontent.com/73228905/228328219-00f90321-737b-4367-a1e8-c9ea611219b5.png)
This happens because the fields are only moddifiable (for some reason), if we have an update button in the page, since we are only showing those on show and update this happens. This does not happens in the lecture form because we are including publish to the list of actions that show these buttons

2023-03-28 18:51 UTC, AntonioRodriguezRuiz commented on src/main/webapp/WEB-INF/views/lecturer/lecture/list.jsp
> +<acme:button code="lecturer.lecture.list.button.create" action="/lecturer/lecture/create"/>
Shouldn't this button behaviour change whether we are or not in a list of lectures of a course? 
Also, if we create a lecture separately, we do not have any way to connect it with a course, should it be better to have the LecturerLectureCreateService always take a courseId? 
In that case, should we show this button in the list of a lecturers own lectures?
Also on the same line, should we be able to create a lecture for a course in draft mode?

Think about this, disscuss whatever needed with the lecturer and comment me

2023-03-28 19:54 UTC, kiinami commented on src/main/java/acme/features/lecturer/course/LecturerCourseDeleteService.java
> +    }
OK, please note it down

2023-03-28 20:00 UTC, kiinami commented on src/main/webapp/WEB-INF/views/lecturer/lecture/list.jsp
> +<acme:button code="lecturer.lecture.list.button.create" action="/lecturer/lecture/create"/>
This is not requested in the requirements, nor is implemented in the starter projects. Please note it down for the follow-up.

2023-04-10 06:49 UTC, victoriaemc commented on src/main/java/acme/features/lecturer/course/LecturerCourseCreateService.java
> +        if (!super.getBuffer().getErrors().hasErrors("code")) {
This code will make an error message appear on the form if the user doesn't change the course's code each time some other field (Title, abstract... etc) is modified.

2023-04-18 15:20 UTC, AntonioRodriguezRuiz requested changes

2023-04-18 15:20 UTC, AntonioRodriguezRuiz commented on src/main/java/acme/features/lecturer/courseLecture/LecturerCourseLectureRepository.java
> +    Collection<Lecture> findManyLecturesNotInCourse(int id);
Also, in case you consider the lecturer here you must also do so in the authorise method when adding a lecture to a course by checking that the lecture is either null or belongs to the lecturer with
```java
lectureId = super.getRequest().getData("lecture", int.class);
```

2023-04-20 10:53 UTC, AntonioRodriguezRuiz requested changes

2023-04-20 10:53 UTC, AntonioRodriguezRuiz commented on src/main/java/acme/features/lecturer/courseLecture/LecturerCourseLectureAddToCourseService.java
> +    }
You should validate that the lecture being added is from the lecturer

2023-04-20 10:53 UTC, AntonioRodriguezRuiz commented on src/main/webapp/WEB-INF/views/lecturer/course/messages-en.i18n
> +lecturer.course.form.error.no-lectures = A course cannot be published without lectures
This message also needs to be present in the spanish version

2023-04-20 13:05 UTC, AntonioRodriguezRuiz requested changes

2023-04-20 13:05 UTC, AntonioRodriguezRuiz commented on src/main/java/acme/features/lecturer/courseLecture/LecturerCourseLectureAddToCourseService.java
>      }
you are checking that the lecturerId is equal to the lectureId?? I meant that the lecture has to belong to the lecturer. This will only allow the lecture with the same Id as the lecturer to be added

2023-04-20 15:29 UTC, kiinami commented on src/main/java/acme/features/lecturer/courseLecture/LecturerCourseLectureAddToCourseService.java
>      }
You are right, this is very stupid

2023-04-20 16:36 UTC, AntonioRodriguezRuiz approved these changes

2023-04-20 17:05 UTC, AntonioRodriguezRuiz approved these changes

2023-04-20 17:06 UTC, merged