Company account
DP2-C1-01-03/Acme-L3-D03 pull request #90
Opened 2023-03-29 13:13 UTC by bogdanstefan

2023-03-30 09:42 UTC, kiinami requested changes
Falta el update (4/12)

2023-04-17 12:19 UTC, bogdanstefan commented
> Falta el update (4/12)

Hecho

2023-04-18 14:12 UTC, kiinami requested changes
Sigue faltando el update (4/12), no ha habido cambios desde la última revisión

2023-04-18 14:12 UTC, kiinami commented on src/main/webapp/WEB-INF/views/fragments/menu.jsp
> +			<acme:menu-suboption code="master.menu.user-account.company" action="/authenticated/company/update" access="hasRole('Company')"/>
this should point to /authenticated/company/show

2023-04-20 10:56 UTC, kiinami requested changes

2023-04-20 10:56 UTC, kiinami commented on src/main/webapp/WEB-INF/views/authenticated/company/form.jsp
> +  <acme:input-textbox code="authenticated.company.form.label.summary" path="summary"/>
Esto mejor de `textarea`

2023-04-20 11:14 UTC, merged